-- ============================================================
-- ORIMETIER — Bandeau d'annonce admin (site-wide)
-- PHASE 2 : passage du singleton (id=1 unique) à une liste de
-- jusqu'à 5 annonces actives simultanément (texte et/ou image
-- mélangés), affichées en rotation côté client.
--
-- Ce script :
--   1) retire la contrainte CHECK (id = 1) et transforme "id" en
--      colonne auto-incrémentée (identity), en réutilisant la
--      valeur déjà en base si une annonce id=1 existe ;
--   2) ajoute created_at (utile pour ordonner la rotation) ;
--   3) remplace admin_publier_annonce / admin_retirer_annonce par
--      3 nouvelles RPC : admin_upsert_annonce (créer/modifier une
--      annonce précise), admin_set_annonce_active (activer/
--      désactiver une annonce précise, avec blocage d'une 6e
--      annonce active si 5 sont déjà actives) et
--      admin_supprimer_annonce (supprimer définitivement une
--      annonce désactivée, pour nettoyer les brouillons inutiles).
--
-- Aucune donnée existante n'est perdue : si une annonce id=1 était
-- déjà publiée, elle est conservée telle quelle (juste id=1, comme
-- avant), et devient la 1ère de la liste.
--
-- La policy RLS "Lecture publique" existante n'a pas besoin de
-- changer : elle autorise déjà la lecture de toutes les lignes
-- (actives ou non), ce qui convient aussi bien à la barre publique
-- (filtrée côté client sur active=true) qu'à la liste admin
-- (qui doit voir les inactives aussi).
--
-- À exécuter en une fois dans l'éditeur SQL de Supabase.
-- ============================================================

-- ---- 1) Retirer la contrainte singleton (CHECK id = 1) ----
-- Recherche dynamique du nom de la contrainte (générée automatiquement
-- par Postgres), pour ne pas dépendre d'un nom supposé.
DO $$
DECLARE
  c record;
BEGIN
  FOR c IN
    SELECT conname FROM pg_constraint
    WHERE conrelid = 'public.annonce'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) ILIKE '%id = 1%'
  LOOP
    EXECUTE format('ALTER TABLE public.annonce DROP CONSTRAINT %I', c.conname);
  END LOOP;
END $$;

-- ---- 2) id devient auto-incrémenté (au lieu de toujours valoir 1) ----
ALTER TABLE public.annonce ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.annonce ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
-- Redémarre la séquence après le plus grand id existant (1 s'il y a déjà
-- une annonce, sinon la prochaine insertion partira de 1).
SELECT setval(
  pg_get_serial_sequence('public.annonce', 'id'),
  COALESCE((SELECT MAX(id) FROM public.annonce), 0) + 1,
  false
);

-- ---- 3) created_at, pour ordonner la rotation par ancienneté de publication ----
ALTER TABLE public.annonce ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

COMMENT ON TABLE public.annonce IS 'Bandeau d''annonce admin : jusqu''à 5 lignes actives simultanément (active=true), affichées en rotation site-wide. Les lignes inactives gardent leur contenu pour republication rapide.';

-- ---- 4) Nouvelles RPC (remplacent admin_publier_annonce / admin_retirer_annonce) ----
DROP FUNCTION IF EXISTS public.admin_publier_annonce(text, text, text, text);
DROP FUNCTION IF EXISTS public.admin_retirer_annonce(text);

-- Crée (p_id = null) ou modifie le contenu (p_id renseigné) d'une annonce.
-- À la création, l'annonce est publiée immédiatement (active=true), sauf si
-- 5 annonces sont déjà actives (retourne alors null, rien n'est créé).
-- En modification, seul le contenu change ; le statut actif/inactif n'est
-- jamais touché ici (voir admin_set_annonce_active pour ça).
-- Retourne l'id de la ligne créée/modifiée, ou null si refusé.
CREATE OR REPLACE FUNCTION public.admin_upsert_annonce(
  p_admin_password text, p_id int, p_type text, p_texte text, p_image_url text
)
 RETURNS int
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_id int;
begin
  if not exists (select 1 from admin_config where id = 1 and admin_password = p_admin_password) then return null; end if;
  if p_type not in ('texte','image') then return null; end if;
  if p_type = 'texte' and length(trim(coalesce(p_texte,''))) = 0 then return null; end if;
  if p_type = 'image' and length(trim(coalesce(p_image_url,''))) = 0 then return null; end if;

  if p_id is null then
    if (select count(*) from annonce where active = true) >= 5 then
      return null;
    end if;
    insert into annonce(type, texte, image_url, active, created_at, updated_at)
      values (p_type, p_texte, p_image_url, true, now(), now())
      returning id into v_id;
  else
    update annonce set type = p_type, texte = p_texte, image_url = p_image_url, updated_at = now()
      where id = p_id
      returning id into v_id;
  end if;
  return v_id;
end; $function$;

-- Active ou désactive une annonce précise. Refuse l'activation (retourne
-- false, ne change rien) si 5 autres annonces sont déjà actives.
-- La désactivation est toujours autorisée et conserve le contenu.
CREATE OR REPLACE FUNCTION public.admin_set_annonce_active(
  p_admin_password text, p_id int, p_active boolean
)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if not exists (select 1 from admin_config where id = 1 and admin_password = p_admin_password) then return false; end if;

  if p_active then
    if (select count(*) from annonce where active = true and id <> p_id) >= 5 then
      return false;
    end if;
  end if;

  update annonce set active = p_active, updated_at = now() where id = p_id;
  return found;
end; $function$;

-- Supprime définitivement une annonce désactivée (nettoyage des brouillons).
-- Refuse la suppression d'une annonce encore active : il faut d'abord la
-- désactiver via admin_set_annonce_active, pour éviter de faire disparaître
-- une annonce publiée par erreur en un seul clic.
CREATE OR REPLACE FUNCTION public.admin_supprimer_annonce(p_admin_password text, p_id int)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if not exists (select 1 from admin_config where id = 1 and admin_password = p_admin_password) then return false; end if;
  delete from annonce where id = p_id and active = false;
  return found;
end; $function$;
