-- ============================================================
-- ORIMETIER — Compteur de visites (statistiques par jour/page, admin uniquement)
-- PHASE 1 : table de log brut + les 2 fonctions RPC (écriture publique,
-- lecture admin).
--
-- Modèle : log brut (1 ligne par visite), agrégé à l'affichage par
-- admin_get_visite_stats — pas de table pré-agrégée (voir diagnostic).
--
-- RLS : à la différence de annonce/liens_formation (lecture publique par
-- policy, écriture verrouillée en RPC), ici c'est l'inverse. Plutôt que de
-- composer des policies RLS "INSERT public / SELECT admin" sur la table,
-- on reprend le modèle déjà utilisé par demandes_inscription_etablissements
-- et les inscriptions publiques (etablissement_register, eleve_register) :
-- RLS activée SANS AUCUNE POLICY (donc aucun accès direct via l'API REST,
-- ni lecture ni écriture, pour personne), et les 2 seules portes d'entrée
-- sont des fonctions SECURITY DEFINER :
--   - log_visite(p_page)               : callable par anon/authenticated,
--                                         sans mot de passe (simple compteur
--                                         de passage, pas une donnée sensible).
--   - admin_get_visite_stats(password) : vérifie admin_config.admin_password,
--                                         comme toutes les autres routes admin.
--
-- test.html est exclu du comptage (pas une vraie page consultée par les
-- utilisateurs) : log_visite() n'accepte que les 7 pages réelles du site.
--
-- À exécuter en une fois dans l'éditeur SQL de Supabase.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.visites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page text NOT NULL,
  visited_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.visites IS 'Log brut d''une ligne par chargement de page (pas de distinction visiteur unique/rôle). Agrégé par jour/page via admin_get_visite_stats. Écrit uniquement via log_visite(), lu uniquement via admin_get_visite_stats().';

CREATE INDEX IF NOT EXISTS visites_page_visited_at_idx ON public.visites (page, visited_at);

ALTER TABLE public.visites ENABLE ROW LEVEL SECURITY;
-- Aucune policy créée intentionnellement : tout accès direct via l'API REST
-- (anon ou authenticated, lecture comme écriture) est refusé. Seules les 2
-- fonctions SECURITY DEFINER ci-dessous peuvent lire/écrire cette table.

-- Enregistre une visite. Callable publiquement (n'importe quelle page, sans
-- connexion), c'est pourquoi p_page est validé contre la liste fermée des 7
-- pages réelles du site plutôt qu'accepté tel quel : évite qu'une chaîne
-- erronée ou farfelue ne vienne polluer le tableau de bord. Retourne false
-- (sans rien insérer) si p_page ne correspond à aucune page connue.
CREATE OR REPLACE FUNCTION public.log_visite(p_page text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if p_page not in (
    'index.html', 'general.html', 'superieur.html', 'concours.html',
    'eleves.html', 'espaces.html', 'liens-formation.html'
  ) then
    return false;
  end if;

  insert into visites(page, visited_at) values (p_page, now());
  return true;
end; $function$;

-- Statistiques agrégées par jour et par page, réservées à l'admin (comme
-- admin_list_demandes_inscription_etablissements, on lève une exception —
-- pas un simple false/null — sur mot de passe invalide, puisque c'est une
-- fonction qui renvoie une TABLE).
CREATE OR REPLACE FUNCTION public.admin_get_visite_stats(p_admin_password text)
 RETURNS TABLE(page text, jour date, visites bigint)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if not exists (select 1 from admin_config where admin_config.id = 1 and admin_config.admin_password = p_admin_password) then
    raise exception 'unauthorized';
  end if;

  return query
    select v.page, v.visited_at::date as jour, count(*)::bigint as visites
    from visites v
    group by v.page, v.visited_at::date
    order by jour desc, v.page asc;
end; $function$;
